### ISSUE TITLE
Bottom bar bug when pasting URL for the first time

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#4379] opened 2022-09-16 18:48 UTC
I noticed when pasting in the URL bar the first time that the bottom bar gets really big. It only seems to happen after I see the paste permission dialog.

https://user-images.githubusercontent.com/979929/190710095-7eb44c0e-159a-4d4c-8ac5-9f26a2f5e90a.MP4

**Comment by darinwf** [comment] 2022-09-16 19:00
@evancrow - any ideas what could be causing this bug?

**Comment by darinwf** [comment] 2022-09-16 19:00
@jedireza - which version of the app are you seeing this in?

We could probably try doing a bisect across existing TestFlight builds and then custom builds from different commits to see which commit caused this regression (assuming it is a regression).

**Comment by evancrow** [comment] 2022-09-16 19:01
No idea. I'll take a look though.

**Comment by evancrow** [comment] 2022-09-16 19:01
It also looks like the GridSwitcher bg colors are wrong.

**Comment by evancrow** [comment] 2022-09-20 04:07
After more investigation, here's what I know:

The copy/paste popover breaks the SafeArea, pushing up the `BottomBar`. That popover has been confirmed by Apple (in most cases) as a bug. I wonder if it's best to leave this for now and let Apple fix it on their end. Once the popover is dismissed, the SafeArea still thinks the keyboard is there and doesn't update to the correct value.

**Comment by evancrow** [comment] 2022-09-21 23:40
I'm reading that Apple fixed this in 16.1 B2, but it still occurs on my device :(

**Comment by evancrow** [comment] 2022-09-29 02:41
This has been fixed in 16.1 Beta 3

**Comment by evancrow** [comment] 2022-09-29 15:31
My guess: next month. I've been trying to find a fix by `ignoringSafeArea` but that modifier has no effect on the bottom bar for no reason I could find.

**Closed** 2022-10-14 21:59 UTC
Labels: bug
