### ISSUE TITLE
Neeva taking 20 seconds to load

### ISSUE THREAD

**Issue by MatejaSrejic** [neevaco/neeva-ios#3966] opened 2022-07-02 16:11 UTC
Neeva version: 1.47.5
iOS version: 16

https://user-images.githubusercontent.com/75619038/177008119-85980385-b7ff-42c0-b77a-aa703481c45f.MOV

**Comment by darinwf** [comment] 2022-07-03 20:31
Thank you for the bug report.

It would be interesting to know how many tabs you have, including archived tabs.

A way to find out how many tabs you have is to choose the option to close all tabs, which will show a confirmation prompt that mentions how many tabs you are about to close. Then just cancel out from that dialog. Same with the archived tabs. You can go to the archived tabs section and hit the close all archived tabs option and see what it reports about the number of archived tabs.

Thanks!

**Comment by MatejaSrejic** [comment] 2022-07-03 20:59
72. I have 72 tabs.

**Comment by evancrow** [comment] 2022-07-06 18:51
I have 500+ tabs on iOS 16, not able to repro this.

**Comment by MatejaSrejic** [comment] 2022-07-09 08:51
> I have 500+ tabs on iOS 16, not able to repro this. What device are you using?

I'm on XR, iOS 16 as well.

**Comment by MatejaSrejic** [comment] 2022-07-17 09:38
Yes, 72 is the total number (72 active + 0 archived)

**Comment by MatejaSrejic** [comment] 2022-07-21 12:25
It's not any better.

**Comment by jedireza** [comment] 2022-11-23 04:42
@MatejaSrejic I've been cleaning up our GitHub issues. I know this is a couple months old now. Are you still experiencing issues with this? Like some have said it seems like somewhat of  anomaly that we can't reproduce, which are some of the trickier bugs to resolve.

I'm going to close this issue for now. But please do reach out again here or in the Makers slack so we can continue to debug.

**Closed by jedireza** 2022-11-23 04:42 UTC
Labels: makers
