### ISSUE TITLE
Sometimes navigating to Neeva OS Settings just takes the user to the top of the OS Settings

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3445] opened 2022-04-25 20:48 UTC
This impacts our Default Browser flow. Some users don't get taken into the Neeva browser settings at the OS level. As a result, they have trouble finding where to set default browser. It seems like the API call we are making is somehow flaky. It is hard to repro the issue, but I've seen new users encounter it.

**Comment by darinwf** [comment] 2022-04-25 21:06
Looks like we are not alone in seeing this bug:
https://developer.apple.com/forums/thread/111030

That forum page has some theories as to why this is happening. Not sure if I believe those yet.

**Comment by darinwf** [comment] 2022-04-26 18:16
From observed cases where this happened:
> One is on an iPhone 11 15.4.1., another is on version 15.3.1.

**Comment by evancrow** [comment] 2022-04-26 20:19
@darinwf Duplicate of #3423?

**Comment by darinwf** [comment] 2022-04-28 23:45
I wonder if we should try asking users for notification permission first thing when opening the app just to force the OS to recognize that the app has settings. Then by the time they see the default browser prompt, it might be more likely to work. Hmm... @chung-lai - WDYT?

**Comment by chung-lai** [comment] 2022-04-29 00:56
It'll be worth trying for a release as an A/B experiment and see how it helps default browser conversion.

**Comment by jedireza** [comment] 2022-11-22 00:50
If this is still happening, my intuition says there isn't something we can do to fix it. It's also something that's happening outside of our app. It could be related to the device, memory, etc. We don't have many good leads at this point.

**Closed by jedireza** 2022-11-22 00:50 UTC
Labels: bug
