### ISSUE TITLE
The tab zooms out and then zoom in when switching tab

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3152] opened 2022-03-17 21:07 UTC
There seem to be a delay on the zooming in/out animation when switching tab on latest testflight build 1.32.10:

https://user-images.githubusercontent.com/87332578/158894885-22b73d59-12c3-4663-84c5-c720248c70fb.MP4

@evancrow @darinwf

**Comment by darinwf** [comment] 2022-03-17 21:16
Ugh, this looks like it might be a safe area related issue :-(

I wonder if it could be a regression from the recent fixes?

**Comment by chung-lai** [comment] 2022-03-17 21:19
It was not happening in 1.32.9 so it should be coming from #3146. @evancrow, see if it's an easy fix or we can decide whether this is a release blocker.

**Comment by evancrow** [comment] 2022-03-17 21:29
@darinwf Maybe it's this line? `SafeAreaInsets` could be nil, I'll test that out.

```
 browserModel.scrollingControlModel.setHeaderFooterHeight(
                 header: chromeModel.topBarHeight,
                 footer: UIConstants.TopToolbarHeightWithToolbarButtonsShowing
                     + (geom?.safeAreaInsets.bottom ?? 0))
```

**Comment by darinwf** [comment] 2022-03-17 22:12
I added a comment to https://github.com/neevaco/neeva-ios/pull/3146.

**Comment by evancrow** [comment] 2022-03-17 23:25
Closing since #3146 was reverted

**Closed by evancrow** 2022-03-17 23:25 UTC
Labels: bug
