### ISSUE TITLE
"Open App" button on webpages open up app store page

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3872] opened 2022-06-15 21:42 UTC
## Expected behavior

On websites, tapping the "Open App" button on the top banner should open the page in the app.

For example, on a twitch stream, tapping the button should open the same stream in the app if installed. It works in both safari and chrome app.

## Actual behavior

It opens a sheet modal with app store page of the app.

## Steps to reproduce the problem

1. Go to twitch.tv and go to a stream that is broadcasting
2. tap the open app button in the top banner 

## Hardware and software

- Your device: 
- OS version: 15.5
- App version: Neeva Browser 1.45.0 (234)

**Comment by evancrow** [comment] 2022-06-15 23:55
This is because we chose to use `SKStoreProductViewController` and Twitch launches the app via its App Store URL (regardless of if it is installed). Unfortunately, there's no way for our app to know if the app is installed without its scheme, which is not included in the URL. 

Twitch URL: https://apps.apple.com/app/twitch-live-game-streaming/id460177396?pt=325952&mt=8&ct=channel-top_nav

**Comment by evancrow** [comment] 2022-11-01 05:46
@jonathangarelick Do you think this issue has been fixed by your recent changes to App Store links?

**Comment by jedireza** [comment] 2022-11-22 22:10
https://user-images.githubusercontent.com/979929/203431323-4cb9f65b-03c1-46fe-a60c-b536928efbcb.MP4

I tried the same thing in Safari and it has a dialog too.

https://user-images.githubusercontent.com/979929/203431525-4aa1f6b3-b02d-4a26-85e1-f2f8b6b99093.MP4

**Closed by jedireza** 2022-11-22 22:10 UTC
