### ISSUE TITLE
Not navigating to Neeva home upon sign in

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3309] opened 2022-04-05 17:10 UTC
1. install app
2. sign in
3. should navigate to neeva.com home page
4. sign out
5. sign in again

It does not navigate to Neeva home anymore. could be related to the InroView fix. fyi @evancrow.

**Comment by darinwf** [comment] 2022-04-05 17:12
By the way, when we fix this, let's make sure it uses createOrSwitchToTab rather than navigate the current tab as the previous implementation used to do.

**Comment by evancrow** [comment] 2022-04-05 17:14
Super quick fix! Just to confirm, we don't want to switch to the Neeva Home page if we're on the SRP though right?

**Comment by darinwf** [comment] 2022-04-05 17:16
> Super quick fix! Just to confirm, we don't want to switch to the Neeva Home page if we're on the SRP though right?

Hmm.. I can see pros and cons. I guess the pro would be consistency. After sign-in, you get taken to neeva home, always. Con is that you lose your place and what you were doing. Maybe you signed in because you were trying to save a page to spaces. In that case, it seems like we should never open neeva home after signing in. Hmm..

**Comment by evancrow** [comment] 2022-04-05 17:17
Exactly, that's what I thought #3209 was for...

**Comment by darinwf** [comment] 2022-04-05 17:18
hehe. you are right! how about we close this bug as working as intended then?

**Comment by darinwf** [comment] 2022-04-05 17:19
actually, Chung points out that it sometimes navigates to neeva home. maybe we should make it consistent and not do any navigation post sign in?

**Comment by evancrow** [comment] 2022-04-05 17:19
Well, should we still navigate if they are on a page other than SRP? Right now it only navigates if the selected tab is nil.

**Comment by evancrow** [comment] 2022-04-05 17:20
I'll be honest, Neeva Home is not helpful on mobile. That's why I thought it only makes sense to navigate if there isn't an open tab.

**Comment by darinwf** [comment] 2022-04-05 17:20
> Well, should we still navigate if they are on a page other than SRP? Right now it only navigates if the selected tab is nil.

I see. So if on preview home they sign in, they would see the neeva home instead of a blank tab tray. That makes sense.

I think we shouldn't navigate if they are on another page because like i said they might be trying to save the current page to spaces.

**Comment by darinwf** [comment] 2022-04-05 17:21
> I'll be honest, Neeva Home is not helpful on mobile. That's why I thought it only makes sense to navigate if there isn't an open tab.

Yes, i'm coming around to that making sense!

**Comment by evancrow** [comment] 2022-04-05 17:21
Cool, so I guess just leave the current behavior and close this issue?

**Comment by chung-lai** [comment] 2022-04-05 17:26
Right, that seems the behavior that it navigates to neeva home when it doesn't have tab. So I'm fine closing this.

But for user who just signed up for new account, is there value to show them there is indeed a neeva homepage? Or we think suggested sites is good enough to show neeva home.

**Comment by darinwf** [comment] 2022-04-05 17:28
> Right, that seems the behavior that it navigates to neeva home when it doesn't have tab. So I'm fine closing this.
> 
> But for user who just signed up for new account, is there value to show them there is indeed a neeva homepage? Or we think suggested sites is good enough to show neeva home.

I think if they already have a page open then it probably makes sense to not navigate them away from that page.

**Closed** 2022-04-05 17:39 UTC
Labels: bug, release_blocker
